# Generated by Django 5.0.2 on 2024-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_options_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
